const endpointCatalog = [
  {
    endpointId: "ENG-WS-001",
    hostname: "ENG-WS-001",
    os: "Windows 11",
    user: "Aarav S",
    department: "Design Engineering",
    location: "Chennai",
    status: "Active",
    lastSeen: "5 mins ago",
    installedSoftware: ["AutoCAD", "Civil 3D", "Revit"],
  },
  {
    endpointId: "ENG-WS-002",
    hostname: "ENG-WS-002",
    os: "Windows 10",
    user: "Priya N",
    department: "Infrastructure Engineering",
    location: "Bengaluru",
    status: "Active",
    lastSeen: "12 mins ago",
    installedSoftware: ["MicroStation", "STAAD.Pro"],
  },
  {
    endpointId: "ENG-MAC-003",
    hostname: "ENG-MAC-003",
    os: "macOS Sonoma",
    user: "Rohit K",
    department: "Design Engineering",
    location: "Pune",
    status: "Idle",
    lastSeen: "47 mins ago",
    installedSoftware: ["Fusion 360", "Maya"],
  },
  {
    endpointId: "ENG-WS-004",
    hostname: "ENG-WS-004",
    os: "Windows 11",
    user: "Nisha P",
    department: "Project Controls",
    location: "Hyderabad",
    status: "Active",
    lastSeen: "3 mins ago",
    installedSoftware: ["Primavera P6 EPPM", "Primavera Cloud"],
  },
  {
    endpointId: "ENG-WS-005",
    hostname: "ENG-WS-005",
    os: "Windows 10",
    user: "Rahul D",
    department: "Manufacturing Engineering",
    location: "Chennai",
    status: "Active",
    lastSeen: "8 mins ago",
    installedSoftware: ["Tekla Structures", "Tekla Tedds"],
  },
  {
    endpointId: "ENG-MAC-006",
    hostname: "ENG-MAC-006",
    os: "macOS Ventura",
    user: "Kavya M",
    department: "Design Engineering",
    location: "Mumbai",
    status: "Idle",
    lastSeen: "1 hr ago",
    installedSoftware: ["AutoCAD", "BIM Collaborate Pro"],
  },
  {
    endpointId: "ENG-WS-007",
    hostname: "ENG-WS-007",
    os: "Windows 11",
    user: "Shakti V",
    department: "Infrastructure Engineering",
    location: "Bengaluru",
    status: "Active",
    lastSeen: "9 mins ago",
    installedSoftware: ["OpenRoads Designer", "RAM Structural System"],
  },
  {
    endpointId: "ENG-WS-008",
    hostname: "ENG-WS-008",
    os: "Windows 11",
    user: "Meena R",
    department: "Design Engineering",
    location: "Pune",
    status: "Active",
    lastSeen: "2 mins ago",
    installedSoftware: ["3ds Max", "Maya", "AutoCAD"],
  },
  {
    endpointId: "ENG-MAC-009",
    hostname: "ENG-MAC-009",
    os: "macOS Sonoma",
    user: "Arun K",
    department: "Design Engineering",
    location: "Chennai",
    status: "Active",
    lastSeen: "6 mins ago",
    installedSoftware: ["Fusion 360", "Revit"],
  },
  {
    endpointId: "ENG-WS-010",
    hostname: "ENG-WS-010",
    os: "Windows 10",
    user: "Anitha J",
    department: "Project Controls",
    location: "Hyderabad",
    status: "Offline",
    lastSeen: "4 hrs ago",
    installedSoftware: ["Primavera Unifier", "Primavera P6 EPPM"],
  },
  {
    endpointId: "ENG-WS-011",
    hostname: "ENG-WS-011",
    os: "Windows 11",
    user: "Naveen T",
    department: "Manufacturing Engineering",
    location: "Mumbai",
    status: "Active",
    lastSeen: "15 mins ago",
    installedSoftware: ["Tekla Structural Designer", "Tekla Structures"],
  },
  {
    endpointId: "ENG-WS-012",
    hostname: "ENG-WS-012",
    os: "Windows 11",
    user: "Ishaan B",
    department: "Infrastructure Engineering",
    location: "Bengaluru",
    status: "Idle",
    lastSeen: "55 mins ago",
    installedSoftware: ["MicroStation", "OpenRoads Designer", "STAAD.Pro"],
  },
];

export const endpoints = endpointCatalog.map((item) => ({
  ...item,
  softwareCount: item.installedSoftware.length,
}));

export function getEndpointById(endpointId) {
  return endpoints.find((item) => item.endpointId === endpointId);
}
